import { useEffect, useRef, useState } from "react";
import { getSession, resetSession, sendMessage } from "./api";
import RecommendationCard from "./RecommendationCard";
import "./App.css";

const SESSION_KEY = "darukaa_session_id";

export default function App() {
  const [sessionId, setSessionId] = useState(null);
  const [profile, setProfile] = useState(null);
  const [messages, setMessages] = useState([]);
  const [input, setInput] = useState("");
  const [loading, setLoading] = useState(false);
  const [error, setError] = useState(null);
  const bottomRef = useRef(null);

  useEffect(() => {
    const stored = localStorage.getItem(SESSION_KEY);
    getSession(stored || undefined)
      .then((data) => {
        localStorage.setItem(SESSION_KEY, data.session_id);
        setSessionId(data.session_id);
        setProfile(data.profile);
        setMessages(data.messages);
      })
      .catch((e) => setError(String(e)));
  }, []);

  useEffect(() => {
    bottomRef.current?.scrollIntoView({ behavior: "smooth" });
  }, [messages]);

  async function handleSubmit(e) {
    e.preventDefault();
    const text = input.trim();
    if (!text || loading) return;
    setInput("");
    setLoading(true);
    setError(null);
    try {
      const data = await sendMessage(sessionId, text);
      setProfile(data.profile);
      setMessages(data.messages);
    } catch (err) {
      setError(String(err));
    } finally {
      setLoading(false);
    }
  }

  async function handleReset() {
    setLoading(true);
    setError(null);
    try {
      const data = await resetSession(sessionId);
      localStorage.setItem(SESSION_KEY, data.session_id);
      setSessionId(data.session_id);
      setProfile(data.profile);
      setMessages(data.messages);
    } catch (err) {
      setError(String(err));
    } finally {
      setLoading(false);
    }
  }

  return (
    <div className="layout">
      <aside className="sidebar">
        <h2>Land profile (inferred)</h2>
        {profile && profile.summary_lines.length > 0 ? (
          <ul>
            {profile.summary_lines.map((line, i) => (
              <li key={i}>{line}</li>
            ))}
          </ul>
        ) : (
          <p className="muted">Nothing captured yet — describe the land in the chat.</p>
        )}
        {profile && profile.missing_critical_fields.length > 0 && (
          <p className="muted small">
            Still missing: {profile.missing_critical_fields.join(", ")}
          </p>
        )}
        <button onClick={handleReset} disabled={loading}>
          Reset conversation
        </button>
      </aside>

      <main className="chat">
        <header>
          <h1>🌱 Biodiversity Intelligence Agent</h1>
          <p className="muted">
            Describe a piece of land. Recommendations are drawn from a curated, cited
            intervention table — not generated by a language model — so effect sizes are
            never invented.
          </p>
        </header>

        <div className="messages">
          {messages.map((msg, i) => (
            <div key={i} className={`message ${msg.role}`}>
              <p>{msg.text}</p>
              {msg.recommendations?.map((rec, j) => (
                <RecommendationCard key={j} rec={rec} />
              ))}
            </div>
          ))}
          {loading && <div className="message assistant muted">thinking…</div>}
          {error && <div className="message error">{error}</div>}
          <div ref={bottomRef} />
        </div>

        <form className="composer" onSubmit={handleSubmit}>
          <input
            value={input}
            onChange={(e) => setInput(e.target.value)}
            placeholder="Describe the land, or answer the question above..."
            disabled={loading || !sessionId}
          />
          <button type="submit" disabled={loading || !sessionId || !input.trim()}>
            Send
          </button>
        </form>
      </main>
    </div>
  );
}
